name: Build With CMake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Configure
       run: cmake -DInternalUtils_BUILD_TEST=ON -DInternalUtils_AUTO_RUN_TEST=ON .
     - name: Build
       run: make
     - name: Test Output
       run: ./Source/InternalUtils > out.ans && diff out.ans Test/inp.ans
       
